### ISSUE TITLE
error while running examples related to the mesh file

### ISSUE THREAD

**Issue by ebrahimnorouzi** [simphony/simdome_wet_synthesis#1]
There is an error by running two examples: 

python compartment_precNMC.py

```
- Cuds object:
  uuid: 88760b65-ebcb-4872-9e0a-5da891be3caf
  type: wet_synthesis.CompartmentNetwork
  superclasses: cuba.Class, cuba.Entity, wet_synthesis.CompartmentNetwork
  description:
    To Be Determined


Traceback (most recent call last):
  File "compartment_precNMC.py", line 52, in <module>
    session.run()
  File "/usr/local/lib/python3.7/dist-packages/osp_core-3.4.0-py3.7.egg/osp/core/session/wrapper_session.py", line 17, in f
    func(session, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/osp_core-3.4.0-py3.7.egg/osp/core/session/sim_wrapper_session.py", line 18, in run
    self._initialize(root_obj, added)
  File "/usr/local/lib/python3.7/dist-packages/simdome_wet_synthesis-1.0.0-py3.7.egg/osp/wrappers/wet_synthesis_wrappers/compartment_session.py", line 116, in _initialize
    raise Exception()
Exception
```

**Comment by mshiea** [comment]
As I mentioned in the meeting, the solvers can't be run until the mesh files are provided to them. Unfortunately, we can't publish the current mesh files that we have since they are confidential!
